### ISSUE TITLE
CHORD is not implemented

### ISSUE THREAD

**Issue by natemara** [processing-js/processing-js#113]
In the Java implementation of processing, there is a constant called `CHORD` defined, this is used for the drawing of arcs. I see that there was an issue opened on lighthouse, but it still doesn't work. I should get this ![Imgur](http://i.imgur.com/0ATZcvb.png), from this code 

```java
arc(50, 50, 80, 80, 0, PI+QUARTER_PI, 2);
```

but nothing shows up, and I see the error: `Processing.js: Unable to execute pjs sketch: ReferenceError: 'CHORD' is undefined` in the browser console.

The value of `CHORD` in Java processing is the int `2`, and when I tried using 2 instead of `CHORD` in processing.js, I got this shape: ![Imgur](http://i.imgur.com/74Qqhjg.png)

**Comment by Pomax** [comment]
fixed with #246
