### ISSUE TITLE
Unable to catch Index Out Of Bounds Exception

### ISSUE THREAD

**Issue by zachooz** [processing-js/processing-js#133]
Try catch error handling is used in both java and javascript in a very similar manner.

It would be nice if the processing js converter was able to take try and catch statements.

As of now, the lines for try and catch just produce errors or are completely ignored.

**Comment by Pomax** [comment]
Can you be more specific? The following code works just fine, as demonstrated over on http://jsbin.com/ciqivelapo/1/
```
  void setup() {
    try {
      size(200,200);
    } catch (Exception e) {
      println(e)
    }
  }
  void draw() {
    try {
      background(255,0,255);
    } catch (Exception e) {
      println(e);
    }
  }
```

**Comment by GoToLoop** [comment]
A more complex example that uses `throw` keyword along _**Error**_ class:  :P  

// http://forum.processing.org/two/discussion/7317/compatible-java-exceptions
```processing
Dummy d;
 
void setup() {
  try {
    d = new Dummy(-10);
    //d = new Dummy(100);
  }
 
  catch (Error cause) {
    println("Oh noes!");
  }
 
  println(d);
  exit();
}
 
public class Dummy {
  int n;
 
  Dummy(int nn) {
    if (nn <= 0)  throw new Error("Positive non-zero values only!");
    n = nn;
  }
 
  String toString() {
    return n + "";
  }
}
```

**Comment by zachooz** [comment]
Hmmm so throw is part of processing js.

This code worked in processing:

try {//1
	buttons[i-1][a-1].addValue();
} catch (Throwable e) { 
	System.out.println("Out of bounds.");
}

However when I put it online, the developer console gave an error saying:

Uncaught reference error, System is not defined. (Probably referring to System.out.println)

When I remove the: System.out.println("Out of bounds.");

EX:

try {//1
	buttons[i-1][a-1].addValue();
} catch (Throwable e) { 
}

The error doesn't appear but the code inside the try block is never run whether it should throw an error or not.

**Comment by zachooz** [comment]
Ah I assumed throw wasn't working for everything however I was mistaken.

Throw in pjs just seems to not work with index out of bounds exceptions.

Here is an example:

```
void setup(){
	size(500,500);
	background(255);
	fill(0);
	int[] ints = {1,2};
	try {//5
		System.out.println(ints[100]);
	} catch (Throwable e) {
		System.out.println("Out of bounds");
	}
	rectMode(CENTER);
	rect(250,250, 50,50);
}

```

The rect will never be drawn and the developer console will output:

Unable to execute pjs: System is not defined.

Here is an example using the code I pasted above: http://zachooz.github.io/ThrowTest/

**Comment by GoToLoop** [comment]
>> I've just assumed `throw` and `catch` statements weren't integrated in pjs...

* Actually keywords `throw`, `try`, `catch`, `finally`, etc. happen to exist both in Java & JavaScript!
* That's why they work b/c Java & JS coincidentally share those keywords and some other APIs!
* However, class _**System**_ doesn't exist in JS and nor PJS (JS Mode) provides such conversion!
* We should stick to Processing's API in order to raise the chance to a succesful transpilation to JS!

**Comment by GoToLoop** [comment]
### Unable to catch *__Index Out Of Bounds Exception__*

JS's arrays are dynamic. And they don't throw any errors if we use an outta bounds index:  @_@
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array

**Comment by zachooz** [comment]
It was the System.out.println. 

Throw and catch work.  

Thanks!

**Comment by GoToLoop** [comment]
Hmmm. Perhaps PJS wraps the array object in order to behave like Java, disallowing index outta bounds! Glad it works!  :D

**Comment by Pomax** [comment]
Remember that Pjs is *not* a JVM, in the slightest. It supports the try/catch syntax that Processing says it supports, and nothing more than that. In javascript, there is no "array index out of bound" error, because arrays have no true size.
