### ISSUE TITLE
[processingjs.org] obsolete link to lighthouse for reporting bugs

### ISSUE THREAD

**Issue by matteosistisette** [processing-js/processing-js#139]
I'm reporting this here because https://github.com/processing-js/processing-js.github.io doesn't seem to have an issue tracker. 

At http://processingjs.org/reference/
where it says "If you encounter any problems with these commands or their documentation please file a bug"
the link points to:
http://lighthouseapp.com/signup?account%5Bname%5D=processing-js

which no longer exists (since a prettly long time ago, if I'm not mistaken)

**Comment by Pomax** [comment]
Thanks for reporting this! We updated the "community" link for issues to point to github, but clearly we forgot about the reference page. I've pushed an update to fix that over at https://github.com/processing-js/processing-js.github.io/commit/bf4f5b94831a74257936b45936fe82caecd3b62c

**Comment by matteosistisette** [comment]
Hi,
Also at http://processingjs.org/ the link to "Bug Tracker" on the right column links to the obsolete lighthouse bugtracker as well.

**Comment by matteosistisette** [comment]
And here too
http://processingjs.org/community/

**Comment by Pomax** [comment]
filed on the site repo as https://github.com/processing-js/processing-js.github.io/issues/21
