### ISSUE TITLE
print() and println() not consistent with Processing: only print one parameter

### ISSUE THREAD

**Issue by matteosistisette** [processing-js/processing-js#141]
Processing's print() and println() functions can be called with more than one parameter and will print all of them separated by space.

ProcessingJS's print() and println() only prints the first parameter and ignores all the other ones.

Example code:
println("a", "b", "c");

Processing output: a b c
Processing JS output: a

**Comment by mendax-grip** [comment]
It's fixed right? Doesn't seem it's there anymore.

**Comment by Pomax** [comment]
`print` and `println` are currently still single argument functions instead of arbitrary length input. No patch has been written yet.

**Comment by eligrey** [comment]
Sounds like you want to use `Array.prototype.join.call(arguments, " ")` in the start of print and println.

**Comment by Pomax** [comment]
pretty much, yeah.

**Comment by Pomax** [comment]
that was actually a bit more work, but patched in https://github.com/processing-js/processing-js/commit/7bb5d8169b9426b3a6fd9be92fb546e2d5940b15, release `1.4.11` on npm and bower.
