### ISSUE TITLE
Sometimes errors are thrown from inside processing.js code and without any stack trace

### ISSUE THREAD

**Issue by teo1978** [processing-js/processing-js#147]
That should never, ever happen.
processing.js should always do all the due checks and throw its own error messages giving error messages that always point to sketch code, not internal code.
And if this really not possible, at the very least it should be ensured that exceptions are thrown in such a way that they are traceable.

Usually when you see a JavaScript error in the javascript console, you can expand it and see its stack trace. Many times, when exceptions occur inside processing.js, you only have a line of code of processing.js gives no information about where the error is originated from.
I'm under the impression that this is due to the fact that processing.js sometimes cacthes and rethrows exceptions, but I'm not completely sure.
All I know for sure is that this cannot-debug-a-thing hell is avoidable.

**Comment by teo1978** [comment]
The second part (i.e. not being able to see stack traces of exceptions thrown from inside processing.js) might actually be a Chrome bug
https://code.google.com/p/chromium/issues/detail?id=464613&thanks=464613&ts=1425606411

**Comment by Pomax** [comment]
Yeah, this has been bothering me for a very long time, too. It's caused in part by https://github.com/processing-js/processing-js/blob/master/src/Processing.js#L4073, which deals with throws that occur at runtime, as well as https://github.com/processing-js/processing-js/blob/master/processing.js#L798

**Comment by Pomax** [comment]
should be fixed as of https://github.com/processing-js/processing-js/commit/eef1454aadff31aea69b5f2368d349d483debcc8 (`v1.4.12`)

**Comment by teo1978** [comment]
I'm not completely sure (I did test just and I did still reproduce the issue with 1.4.12, but it didn't reach that part of the code I see you changed), but **I don't think that would fix this**. Actually, I'm afraid you can't fix it at all.

When you tested it, **did you open the Console *after* producing the error?** 

There is a Google Chrome bug (or design flaw), where stack traces are available only if the Developer Tools are already opened when the exception is thrown.
https://code.google.com/p/chromium/issues/detail?id=464613
So, I'm not sure these changes in how you treat the exception make any difference at all. I suggest to test both versions (before and after the commit) first with the Developer Tools already opened, and then with the Developer Tools closed, opening the console after the error is thrown. If my guess is correct, there won't be any difference between the two versions, and the difference only lies in whether you open Dev Tools before or after.
So, if I'm correct, it should be considered whether this change is desirable or not (given that it doesn't fix the issue at hand)


However I think there could be a (at least partial) workaround, which by the way is also a feature I wanted to ask, which is to print a stacktrace in the same frame where println() writes its output (in red or any special color would be great), using ```e.stack```, where ```e``` is the exception. I guess this would not be possible in all cases, but probably most. The information given by e.stack is also not exactly the same as would be given by the console in dev tools, but it's better than nothing.

Think about novice users coming from Processing. Many of them don't even know about the JavaScript console and feel lost in front of a sketch that doesn't work without (apparently) an error message, especially in the cases where their sketch did work in plain Processing (Java). It would be a great improvement to have error messages show up in a place they don't have to look for, and I think this should be possible through the mechanism that is already in place for println().

**Comment by Pomax** [comment]
yeah the strack trace in the dev console seems to only get generated by browsers if the dev tools are already open, so that part I don't think can be fixed in Pjs, but at the very least we should be able to make the code throw "appropriately" so that a reload with dev tools open gives you the proper break point and stack trace.

Putting the stacktrace in the HTML for the console might be an idea, although it might be only marginally more useful for people new to Processing since it will won't be as "obvious" where things go wrong as when the PDE throws a java stack trace. 

That said, probably worth filing a new issue for seeing if we can get console reporting on a throw-crash to a) work and then b) look good.

**Comment by teo1978** [comment]
Something got worse here with respect to this issue.

Usually, stack traces in the (true) console wouln't be available if the console was opened after producing the error, but they *would* be if the developer tools were already opened before loading the page. That's because of the way Chrome handles exception traces.

However now, at least in some cases, the trace is not available **even with the console previously open**. For example now I'm getting:
```
processing.js:13644 Uncaught TypeError: $this_1.randomSeed is not a function
```
(by the way the very existence of that error is a bug, but I'll file that separately).

I'm not sure why this happens but it seems to me it must be the way in which Processing.js itself catches and re-throws the exception, or something. I've never seen such a thing happen (once you know that you have to open the console before) outside processing.js
