### ISSUE TITLE
XML.toString() broken: prints literal "null" inside empty nodes

### ISSUE THREAD

**Issue by teo1978** [processing-js/processing-js#152]
```
// Processing.js only
XML test=new XML("<root><a/><b/></root>");
println(test);
```
Expected output:
```
<root><a/><b/></root>
```
Actual output:
```
<root><a>null</a><b>null</b></root>
```

Due to other bugs that make Processing.js's XML's API incompatible with Processing's, you can't test the correct behavior on Processing with the exact same code above. However, you can do the test on Processing with the following code:
```
// Processing (Java) only
XML test=parseXML("<root><a/><b/></root>");
println(test);
```
This produces the expected output in Processing.

**Comment by Pomax** [comment]
hm, looks like https://github.com/processing-js/processing-js/blob/master/src/Objects/XMLElement.js#L760 is a little too loose, and should return `""` if the text context is `null`/`undefined`. I'll try to get that patched today and update the XML unit test to test for toString correctness with your case example.

**Comment by Pomax** [comment]
wow, that's an interesting bug. For unit testing purposes (using `jsdom` in node), the combination of `<a/><b/>` is treated as an element called `a/`, and an element `b/`, leading to the bizarre string `<root><a/><b/>null</b/></a/></root>`...

Testing PR #154 with input `<root><a></a><b></b></root>` leads to the correct `<root><a/><b/></root>`, so I've filed #155 to address that. 

There's a unit test that's failing for randomGaussian atm, so I'll need to fix that before the build can pass again, but will update the PR after doing so.

**Comment by teo1978** [comment]
Sorry I don't understand.
I get
```<root><a>null</a><b>null</b></root>```
not
```<root><a/><b/>null</b/></a/></root>```

**Comment by Pomax** [comment]
#154 landed
