### ISSUE TITLE
update XML constructor to only create a node based on the passed node name

### ISSUE THREAD

**Issue by Pomax** [processing-js/processing-js#157]
See https://processing.org/reference/XML.html

This will also require making sure that loadXML keeps working for build XML objects off of a URI.

also see https://github.com/processing-js/processing-js/issues/150

**Comment by teo1978** [comment]
> This will also require making sure that loadXML keeps working for build XML objects off of a URI
https://github.com/processing-js/processing-js/issues/150 ;)

**Comment by Pomax** [comment]
double checked the code we have in place - this is already what the code does if you issue things like `new XML("root")`. Adding a unit test only to ensure no regression takes place.

**Comment by Pomax** [comment]
added in https://github.com/processing-js/processing-js/commit/c5c7d9443530108f48e93b01079c61e6d608facb
