### ISSUE TITLE
PVector.angleBetween(v1, v2) is not consistent when v1 == v2

### ISSUE THREAD

**Issue by viamodulo** [processing-js/processing-js#168]
I noticed that the PVector.angleBetween() function sometimes returns NaN when given twice the same vector as parameter. I would expect it to return 0 (or some very small floating point).

PVector v1 = new PVector(2, 4);
float a = PVector.angleBetween(v1, v1);
println(a);  // Prints "2.1073424255447017e-8"
-> OK

PVector v1 = new PVector(2, 3);
float a = PVector.angleBetween(v1, v1);
println(a);  // Prints "NaN"
-> weird, prints 0 when used with processing 2.2.1

I tested these instances on http://processingjs.org/tools/processing-helper.html as well as on my computer with the developement version 1.4.8.

**Comment by Pomax** [comment]
current dev is 1.4.13, but I'm pretty sure that function wasn't touched since 1.4.8, marking as bug.

**Comment by viamodulo** [comment]
I looked for the implementation of angleBetween and I found this :

PVector.angleBetween = function(v1, v2) {
    return Math.acos(v1.dot(v2) / (v1.mag() * v2.mag()));
  };

The NaN value comes from the fact that sometimes Math.acos() is given a value slightly bigger than 1.
I think the problem comes from rounding issues between multiplying two (identical) square roots (the results of v1.mag() and v2.mag()). Changing the code to :

PVector.angleBetween = function(v1, v2) {
    return Math.acos(v1.dot(v2) / Math.sqrt(v1.magSq() * v2.magSq()));
  };

seems to solve the problem, and reduces the number of calls to Math.sqrt().

**Comment by Pomax** [comment]
nice catch, would  you be up for turning that into a PR?

**Comment by viamodulo** [comment]
I turned it into a pull request. I hope that was the right way of doing things, I never did one before. :)

**Comment by Pomax** [comment]
then hurray, because you did it quite right!

**Comment by Pomax** [comment]
unit test still required

**Comment by viamodulo** [comment]
I added two unit tests, each checking the values I had mentionned in the original post.

**Comment by Pomax** [comment]
you rock!
