### ISSUE TITLE
point() & line() snap to integer coords

### ISSUE THREAD

**Issue by scudly** [processing-js/processing-js#173]
point() and line() ignore the floating-point fractional amounts and snap to the nearest integer.

size(400,400);
line(0, 100, 400, 100);
line(0, 200, 400, 200);
line(0, 300, 400, 300);
line(100, 0, 100, 400);
line(200, 0, 200, 400);
line(300, 0, 300, 400);

scale(100,100);
stroke(255,0,0,192);
strokeWeight( 0.3 );
point( 1.1, 0.5 );
line( 0.5, 2.2, 2.5, 2.8 );
ellipse( 2.7, 1.2, 0.7, 1.3 );

strokeWeight( 1.1 );
point( 0.7, 3.4 );

http://studio.sketchpad.cc/NHztFQHgZV

Java Processing renders them at the proper floating-point coordinate positions.

**Comment by Pomax** [comment]
This is by design, because the Canvas2D api has a very peculiar coordinate system, and using fractional coordinates creates ridiculous antialiassing effects. If you're okay with that, call `smooth()` in your setup, and the compensation techniques will be bypassed.

**Comment by scudly** [comment]
Except that integer coordinates and pixel alignment are two separate issues.  I don't mind if lines and points are pixel aligned, but if I scale up the coordinate system, I should be able to give fractional floating-point coordinates that still map to integer pixel coordinates.

**Comment by Pomax** [comment]
right, so try `smooth()` in your setup.

**Comment by scudly** [comment]
smooth() doesn't make any difference.  The clamping to integers happens independently of rendering.  Paste this into http://processingjs.org/tools/processing-helper.html and see:

smooth();
scale(100);
strokeWeight(0.02);
line(0.25,0.25,0.75,0.75);

In Java, it draws from 25,25 to 75,75.  In processing-js, the line clamps to 0,0 and 100,100 whether or not you include the call to smooth();

**Comment by Pomax** [comment]
hmm, that's probably a bug then. marking.
