### ISSUE TITLE
Cannot get texture() to work: "createTexture is not a function"

### ISSUE THREAD

**Issue by birgitta410** [processing-js/processing-js#177]
Hi,

I am having trouble using texture(). Below is a small example of what I am doing, this gets me "Uncaught TypeError: curContext.createTexture is not a function".

I also tried to call size() with a third parameter P.WEBGL, as I thought it might have something to do with the type of canvas that is initialized, 2D vs. 3D? But no change. Seems like passing that third argument does not change the type of context, in both cases I was seeing 2D drawing contexts when debugging, is that correct?

Also tried setting the different texture modes, e.g. textureMode(IMAGE), textureMode(NORMAL), no change.

Am I missing something, or is this a bug?

```
    var img;
    P.setup = function() {
        P.size(300, 300, P.P2D);
        P.background(255);
        img = P.loadImage('http://processingjs.org/images/header.png', 'png');
    };

    P.draw = function() {
        P.image(img, 0, 0); // Drawing img to make sure it's loaded properly

        P.beginShape();
        P.texture(img); // This fails
        P.vertex(110, 110);
        P.vertex(200, 110);
        P.vertex(200, 200);
        P.vertex(110, 110);
        P.endShape();

    };
```

Here's a fiddle: https://jsfiddle.net/c0j4Lok8/2/

It uses Processing 1.4.7, but I am experiencing the same in 1.4.8 and 1.4.13.

Thanks a lot,
Birgitta

**Comment by GoToLoop** [comment]
Since "header.png" file comes from a remote server, it becomes "tainted"!
For example, if we try `img.loadPixels();  console.info(img.pixels.length);` we'll get undefined.
And even worse, even the canvas become tainted once it stamps a "tainted" `PImage`:  @_@
```js
P.image(img, 0, 0);
P.loadPixels();
console.info(pixels.length);
```
> Uncaught SecurityError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.

**Comment by birgitta410** [comment]
My "createTexture is not a function" error also happens when I use a file served from my own server, I just used the external image in the example to make it easier to reproduce the error for potential helpers.

**Comment by Pomax** [comment]
@GoToLoop  unfortunately, this is a browser security policy that all browser makers agreed on: if you load an image from a different domain, you can't do any kind of editing on it. As just another JavaScript library, Pjs unfortunately has no power to overrule that. However, if you host the image on a server that has CORS settings that say "anyone can use my content as they want", the browser won't lock the image down.

@birgitta410 did you remember to put a `/* @Pjs preload="header.png" */` directive at the top of your sketch? Browsers can't synchronously load images, so we have to force-load them before the sketch starts, or you have to use the requestImage technique described over on the Processing reference, where you check your image width/height during draw() until they're not 0, at which point the image will have loaded in. Without a preload directive, loadImage will yield a null object, so getting a "... is not a function" error would make sense.

**Comment by GoToLoop** [comment]
> you can't do any kind of editing on it.

No need to edit the remote image itself. I just wish I could at least extract its pixels, so I can build a local image from those pixels.
Indeed p5*js framework got that same remote image problem too. But at least I was able to **resize()** those remote images.
In pjs I can't do anything at all!  =(

**Comment by GoToLoop** [comment]
Tweaked PJS's **texture()** example: http://processingjs.org/reference/texture_/
Got some image from: http://processingjs.org/reference/texture_/
And made this 1 up:  :D 

"index.html":
---
```html
<!DOCTYPE html>
<head>

  <meta charset="utf-8">
  <title>PJS-Texture</title>

  <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/processing.js/1.4.8/processing.min.js" defer></script> -->
  <script src="processing.min.js" defer></script>

</head>

<body>

  <h1>☺ PJS-Texture Example ☻</h1>
  <h2>from: http://processingjs.org/reference/texture_/</h2>
  <h3>for:  https://github.com/processing-js/processing-js/issues/177/</h3>

  <script src="sketch.js" type="text/processing"></script>

</body>

<canvas></canvas>
```

"sketch.js":
---
```js
/* @pjs preload = "abstract.jpg, http://processingjs.org/images/exhibition/abstract.jpg" */

size(350, 100, P3D);
smooth();
noStroke();
background(#0080FF);

PImage a = loadImage("abstract.jpg");
//PImage a = loadImage("http://processingjs.org/images/exhibition/abstract.jpg");

set(width/2.5, height>>3, a);

beginShape();
texture(a);
vertex(10, 20, 0, 0);
vertex(80, 5, 100, 0);
vertex(95, 90, 100, 100);
vertex(40, 95, 0, 100);
endShape();
```

Uncomment the line w/ remote URL in order to see the "tainted" bug...  >;-)

**Comment by birgitta410** [comment]
(I think we are talking about two different issues in this thread, maybe this should be split?)

@Pomax: Thanks for your answer. I have not added the preload directive, because I was not sure if that would work in the "pure JS" version that I am using. But to be honest, I also don't think that this is the problem. If you have a look at my fiddle (https://jsfiddle.net/c0j4Lok8/2/), you will see that I am drawing the image itself (not as texture) even before I call texture(), just to make sure loading it was not the issue.

The actual error seems to be an API error to me (you should see it on the console when you run the fiddle). It occurs on this line:
https://github.com/processing-js/processing-js/blob/master/processing.js#L17250

When I debug, at this point the instance of curContext is a CanvasRenderingContext2D. That object does indeed not have a function "createTexture". That's why I suspected I might have to go into 3D mode, but could not get that to work either.

**Comment by GoToLoop** [comment]
Sorta was able to make it run. But **texture()** doesn't seem to be working as expected.
At least not for the host's "logo.png" image: https://jsfiddle.net/c0j4Lok8/3/
```js
new Processing('myCanvas', function (p) {
    var img;

    p.setup = function () {
        p.size(300, 300, p.P3D);

        p.smooth();
        p.stroke(050);
        p.strokeWeight(6);
        p.fill(0350);
        p.background(0100);

        img = p.requestImage('../../img/logo.png');
    };

    p.draw = function () {
        if (!img.width) return;

        p.noLoop();
        p.background(0xff0080FF);
        p.set(p.width - img.width >> 1, p.height >> 4, img);

        p.beginShape();
        p.texture(img);
        p.vertex(110, 110);
        p.vertex(200, 110);
        p.vertex(200, 200);
        p.vertex(110, 110);
        p.endShape();
    };
});
```

**Comment by Pomax** [comment]
@GoToLoop please file a separate issue with your code for the image resizing issue and remove the comments from this thread (it's a completely different issue, better to file it as such and then simply point to that new issue in a comment instead of conflating an issue with two different problems).

**Comment by Pomax** [comment]
@birgitta410 yeah this is worth looking into, it feels like a `p` binding is lost somewhere so that the context ends up being a canvas instance instead of the sketch isntance...

**Comment by greenred123** [comment]
I'm experiencing the same issue - any development on this?

**Comment by greenred123** [comment]
I'm experiencing the same issue! Any developments on this?

**Comment by Pomax** [comment]
none yet (I'm in the middle of a move, and don't expect to have much free time for the next 2 weeks either)

**Comment by greenred123** [comment]
Thanks for the response - good luck with the move!

**Comment by aditya95sriram** [comment]
I am also experiencing the same issue, but this only seems to be a problem when working with P2D renderer and works fine with P3D. Unfornutely, I am forced to using P2D 😢 . Would be great to know if there is any workaround to this.

**Comment by Pomax** [comment]
It would be - please be aware that development has ground to a halt since the last message in this thread, and this repo is no longer under active maintenance.  Please see 
https://github.com/processing-js/processing-js/blob/master/ISSUE_TEMPLATE.md

**Comment by aditya95sriram** [comment]
@Pomax Thanks a lot for letting us know 👍
