### ISSUE TITLE
Processing.js-1.4.15 pure js doesn't work with jQuery-2.1.4

### ISSUE THREAD

**Issue by jabaa** [processing-js/processing-js#192]
Draw() isn't executed in pure javascript code, when Processing.js-1.4.15 is inserted after jQuery-2.1.4 but after changing the order it works. This problem exists since 1.4.9.

index.html

    <!DOCTYPE html>
    <html>
    	<head>
    		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
       		
       		
    		
    		<title>Clock</title>
    	</head>
    	<body>
    		<div id="header">
    			<h1>Clock</h1>
    		</div>
    		<div id="container">
    			<canvas id="canvas" width="100" height="100"></canvas>
    		</div>
    		
    		
    		<script src="bower_components/jquery/dist/jquery.js"></script>
    		<script src="bower_components/Processing.js/processing.js"></script>
    		
    		<script type="text/javascript" src="js/main.js"></script>
    	</body>
    </html>

js/main.js

    (function(){
    	function sketchProc(processing) {
    		processing.draw = function() {		  
    			var centerX = processing.width / 2, centerY = processing.height / 2;
    			var maxArmLength = Math.min(centerX, centerY);    

    			function drawArm(position, lengthScale, weight) {      
    				processing.strokeWeight(weight);
    				processing.line(centerX, centerY, 
    				centerX + Math.sin(position * 2 * Math.PI) * lengthScale * maxArmLength,
    				centerY - Math.cos(position * 2 * Math.PI) * lengthScale * maxArmLength);
    			}

    			processing.background(224);

    			var now = new Date();

    			var hoursPosition = (now.getHours() % 12 + now.getMinutes() / 60) / 12;
    			drawArm(hoursPosition, 0.5, 5);

    			var minutesPosition = (now.getMinutes() + now.getSeconds() / 60) / 60;
    			drawArm(minutesPosition, 0.80, 3);

    			var secondsPosition = now.getSeconds() / 60;
    			drawArm(secondsPosition, 0.90, 1);
    		};
    	}

    	$(document).ready(function(){
    		var canvas = document.getElementById("canvas");
		
    		var p = new Processing(canvas, sketchProc);
        });
    }());

**Comment by Pomax** [comment]
pure JS mode is no longer supported. If you want to use Pjs as a JS graphics library, there are plenty of better libraries available. Pjs since 1.4.9 is purely for running `.pde` source
