### ISSUE TITLE
loadSketchFromSources should have a callback.

### ISSUE THREAD

**Issue by DylanVann** [processing-js/processing-js#203]
It would be useful to be able to know when a sketch is loaded.

In my use case I'm loading sketches in an infinite-scroll situation. Once a sketch is loaded I need to override the dimensions to make it responsive. Polling isn't a great solution.

I don't think I'm the only person who would find this useful. See [this StackOverflow question](http://stackoverflow.com/questions/10281747/how-to-know-when-a-processingjs-sketch-has-been-loaded).

I can submit a pull request, just filing an issue for feedback first.

**Comment by Pomax** [comment]
as a specific-to-Pjs function, adding a callback sounds like a perfectly reasonable idea

**Comment by DylanVann** [comment]
I've added to the pull request: changed the name to onComplete. I probably should have referenced this issue in the commit message.

**Comment by strech345** [comment]
i dont see this collback on the downloadable version 1.4.8 from http://processingjs.org/download/
Are there different branches?

**Comment by GoToLoop** [comment]
https://GitHub.com/processing-js/processing-js/releases
