### ISSUE TITLE
a way to produce custom builds

### ISSUE THREAD

**Issue by kevinbarabash** [processing-js/processing-js#211]
Right now processing.min.js is 233KB.  It would be nice if there was a way to generate builds that support either 2D or 3D drawing instead of packaging both together.

**Comment by GoToLoop** [comment]
PJS' aim is to transpile Processing's "Java Mode" as JS.
Also Processing got the __*PGraphics*__ class which can be 2D or 3D individually.

**Comment by Pomax** [comment]
The amount of space it would save would also be very little, since the bulk of the code is not concerned with 2D/3D. The savings in practice don't live up to the the idea of a tailored library, so given the current code base this won't be worth doing.

**Comment by kevinbarabash** [comment]
@Pomax good to know.
