### ISSUE TITLE
img.copy fails silently

### ISSUE THREAD

**Issue by hungerburg** [processing-js/processing-js#213]
My sketch pre-loads an image and later, during run-time, requests another one asynchronously. When I copy the new image into the old image, nothing happens - This used to work in java processing.

Here an example - http://myzel.net/js/requestImage.html - After five seconds the display should alternate between showing an A and showing a B.

Did I miss something? Have I found a bug? Please share!

**Comment by hungerburg** [comment]
PS: I just added superficial HTTP-GET parameters, so it can be better seen in the debugger, which sketch is fetching what.

**Comment by Pomax** [comment]
do you have the failing sketch running on its own, without output/traffic of the second sketch getting in the way?

**Comment by GoToLoop** [comment]
His sketch the way it is already proves _**PImage**_'s **copy()** is buggy.
The original loaded "AB.png" isn't affected by **copy()**: http://myzel.net/js/AB.png

**Comment by GoToLoop** [comment]
On 2nd thought, he never uses **image()** within **draw()**.
In order to prove _bild_ was altered or not by **requestImage()**'s _next_, the canvas needs to be "refreshed"!

**Comment by Pomax** [comment]
why are canvas and  refreshed in quotes? Can you explain what you mean? (the draw() loop runs at a specific frequency, so sketch updates should already be happening)

**Comment by hungerburg** [comment]
@Pomax Sorry, I was in a hurry, now they are on separate pages, linked to one another, so you can see them on their own

**Comment by hungerburg** [comment]
@GoToLoop An intriguing idea, yet, the original sketch updates quite well with lots of other drawing on the scene; I made a stripped down version which just does, what fails; Though, the original seems to tell me, that the idea is off, should not be an issue: In the reference I also do not see any "repaint" method or such…

**Comment by hungerburg** [comment]
I made another sketch http://myzel.net/js/requestImageCpy2.html that does not show any image at all, though I think, it should…

**Comment by GoToLoop** [comment]
You haven't got what I meant. Since you're altering the original _**PImage**_'s _bild_, you need to re-invoke **image()** in order to actually see its current state in the "canvas".

**Comment by hungerburg** [comment]
@GoToLoop Cool, you nailed it! Cpy2 example updated to prove it. Now, in the original sketch, I NEVER show the image on scene, it is but an off-screen map, that governs the movements of the balls. The sketch reads out its Pixels array. Do you have an idea, how to refresh an off-screen image without flicker, like the img.copy in processing does, that would be great indeed!

**Comment by GoToLoop** [comment]
All images don't show up in canvas until we use **image()**, **set()** or **background()** on them.
As long as steps in **draw()** are fast enough, it should be flickerless.

BtW, these kinds of programming questions should be asked in http://forum.Processing.org/two/.
This is a bug tracker and feature request repository!

**Comment by hungerburg** [comment]
@GoToLoop Thank you for the explanation; I do not think processing forum is the right place, because with processing the sketch works to my full satisfaction, rather this issue is, that processing.js behaves differently. I do not want the image to show, I just want to read its pixels[].

**Comment by hungerburg** [comment]
Thinking about it a little more, in the original sketch, THE SAME URL producces a DIFFERENT image, each time it is called. Probably, that is, where processing.js optimizes away a re-fetch? Gotta look…

**Comment by hungerburg** [comment]
Success: ```nextImg = requestImage(URI + "?rnd=" + Math.random());``` does the trick! So, the lesson learned: processingjs does not load a requested image, if it has been fetched before, unless the URI changes.

**Comment by GoToLoop** [comment]
Processing forum is for all "Modes", including "JavaScript Mode"!
PJS doesn't optimize anything but the browser which caches any resource loadings!

**Comment by Pomax** [comment]
ah, yeah if your server is not generating a cache-busting header, then the browser cache can quite easily get in the way. Glad to hear @GoToLoop identified the problem - is your issue resolved with this?

**Comment by hungerburg** [comment]
Happy here, problem solved, superficial GET parameter with random value is the way to go; Sending headers did not work however, I only tried the first stackexchange proposal though ```header("Cache-Control: no-store, no-cache, must-revalidate, max-age=0");
header("Cache-Control: post-check=0, pre-check=0", false);
header("Pragma: no-cache");```, but this is getting complicated soon.

I understand now, that the processingjs runtime is more advanced than appletviewer or jnlp and that finesse entails headaches sometimes.

**Comment by Pomax** [comment]
Yeah, query argument cache busting is far more effective. Processing.js is a JavaScript library first, with all the fun browser-related things that come with that, and a "Processing parser" second. Glad to hear it got resolved.
