### ISSUE TITLE
Can't use es6 features that my browser supports

### ISSUE THREAD

**Issue by togakangaroo** [processing-js/processing-js#216]
I wrote a `const` in my processing script and got an error `Unexpected token const`. I'm running in chrome which definitely supports `const` so what's the deal? Can I not use javascript features that are supported by my browser?

**Comment by GoToLoop** [comment]
http://ProcessingJS.org/tools/processing-helper.html

```processing
void setup() {
  const a = "I'm a constant.";
  final String b = "I wanna be a const too!";
  println(a);
  println(b);
  exit();
}
```

**Comment by togakangaroo** [comment]
Huh..odd...I might have been on an older version..
