### ISSUE TITLE
Empty scene with ortho() 

### ISSUE THREAD

**Issue by RoboMod** [processing-js/processing-js#221]
In our 3D script we are using the <code>ortho();</code> command to get a lovelier view on the scene. But including this command results in an empty scene. You can even test this effect on http://matrix.senecac.on.ca/~asalga/pjswebide/index.php by adding <code>ortho();</code> to the <code>update();</code> function of any example. 
Checking this problem with Firebug sometimes gives:
````
TypeError: curContext.useProgram is not a function
````
Do you have any idea what's problem here?

**Comment by Pomax** [comment]
hm, I'm not too familiar with the 3D code, but it looks like https://github.com/processing-js/processing-js/blob/master/src/Processing.js#L5594 is relying on code that I can't find getting decared anywhere else in the code...

**Comment by jwdunn1** [comment]
Enter sane clipping arguments and your scenes render perfectly. For example: 
ortho(-width/4, width/4, -height/4, height/4, -500, 500);

**Comment by RoboMod** [comment]
Thanks for this quick solution. We are very happy to see our animations in a browser.
