### ISSUE TITLE
Touch Input Broken

### ISSUE THREAD

**Issue by SamNChiet** [processing-js/processing-js#222]
Sketches running on mobile/touchscreen devices don't respond to touch events.
Mouse functions don't get called at all, and experimenting with the undocumented touch events proved fruitless. Even a sketch as simple as this -

```
void setup() {
  size(300,300);
}

void draw() {
  if( mousePressed ) {
    ellipse(mouseX,mouseY,10,10);
  }
}
```
- doesn't work. Any idea what the issue here is?

Thanks,
Sam

EDIT: These sketches _do_ work in normal browsers on computers

**Comment by Pomax** [comment]
I am not too familiar with the event handling, looking at https://github.com/processing-js/processing-js/blob/master/src/P5Functions/touchmouse.js I suspect it's seeing real touch events and thus isn't falling through to "faking" touch via mouse events. 

You could try and see if this works:
```
[... your code ...]

void touchStart(t) {
  for(int i=0; i<t.touches.length; i++) {
    println(touches[i]);
  }
}
```

**Comment by SamNChiet** [comment]
Whenever I try to run this code, the Processing IDE throws "Error on '... VariableDeclaratorId".
I've tried looking around to find the type of "t" so I can properly declare it, but I've had no luck. Could you shed some light on this? Thanks again.

**Comment by Pomax** [comment]
I'm not too familiar with the touch event system, so https://github.com/processing-js/processing-js/pull/118 might fix this... would you be willing to see if that's the case?

**Comment by SamNChiet** [comment]
I was unaware that Processing.js had other modular components - the website download only contained one file, `processing.js`. Is there something I'm missing?

**Comment by Pomax** [comment]
First grab the current Pjs codebase by using the steps detailed in https://github.com/processing-js/processing-js#playing-with-the-code, then applying the PR to your local code (depending on how you use git on your machine the instructions for that are different and varied. Using the command line it means adding the PR user as remove, doing a `git fetch thatuser`, then a `git merge thatuser/branchname`), and then building a new `processing.js` off of the updated source code by using the `grunt` build command.
