### ISSUE TITLE
processingjs.org/learning/topic/buttons

### ISSUE THREAD

**Issue by Macribo** [processing-js/processing-js#223]
Hi there.

Looks like a typo in the buttons tutorial:
http://2.bp.blogspot.com/-z0C_u0DCiCU/VpgZ9_3lZDI/AAAAAAAAAy4/TrW5EPNWXXw/s1600/Define_and_create.png

Commented text says it's defining and creating a rectangle button but code is creating a circle button.

best regards
Roibeárd

**Comment by Pomax** [comment]
given the name, the comment is wrong, not the actual code itself. filed as https://github.com/processing-js/processing-js.github.io/issues/27
