### ISSUE TITLE
long datatype not supported?

### ISSUE THREAD

**Issue by Pomax** [processing-js/processing-js#224]
For some quick maths sketching I figured I'd use the following lookup table:
```
long[] facts = {
  1, 1, 2, 6, 24, 120, 720, 5040, 40320, 362880, 3628800, 39916800, 479001600, 6227020800, 87178291200, 1307674368000
};

void setup() { noLoop(); }
void draw() {}
```
but when running this, I get the error that 6227020800 doesn't fit in an `int`. Which is true. But also not the datatype I was telling it to use. Both the Processing API and the JVM supports the long datatype, so I'm pretty sure this is a bug? https://processing.org/reference/long.html at least claims it should do what I would expect it to do.

**Comment by GoToLoop** [comment]
Java language obliges us to suffix any integral literal that goes beyond 2 ** 31 w/ `L` or `l`:
6227020800L, 87178291200L, 1307674368000L

**Comment by GoToLoop** [comment]
I've gone to http://ProcessingJS.org/tools/processing-helper.html and tested the `L` suffix there.
It doesn't work! And got diff. errors depending on the case of the suffix's letter!
Pjs got no problems w/ suffix `f` nor `F` though. Check it out:

---
```Processing
float f = 2f;
float F = 2F;

long l = 3l;
long L = 3L;

final long[] longs = { 100f, 200F, 1000L, 2000l };
```

---

```js
// this code was autogenerated from PJS
(function($p) {

    var f = 2;
    var F = 2;

    var l = 3l;
    var L = 3L;

    var longs = [100, 200, 1000L, 2000l];
})
```

---

**Comment by Pomax** [comment]
hah. I filed this on the wrong repo. That should have been on the plain processing issue tracker.
