### ISSUE TITLE
cannot copy error messages

### ISSUE THREAD

**Issue by Pomax** [processing-js/processing-js#225]
The Processing 3.0.1 doesn't let me copy error messages, so I can't use them when asking people for help or filing bug reports. Instead I get  "resize" cursor and I can move the console up and down, but I can't text-select the error that I'm getting.

**Comment by GoToLoop** [comment]
B/c I'm still @ version 3.0.0 I still haven't felt nor even knew about that!
I'm waiting next version to make an update.  :P

**Comment by Pomax** [comment]
filed on the wrong tracker.
