### ISSUE TITLE
text() not working in Firefox

### ISSUE THREAD

**Issue by Gutza** [processing-js/processing-js#232]
I'm sure I can't be the first to notice this, but text() and friends don't work in Firefox, and I haven't been able to find **any** resource explaining the reason – neither an open or closed issue, nor a known bug in the FAQ, nor in fact anything on the web. The issue is quite easy to replicate: open the "official" [letters](http://processingjs.org/learning/basic/letters/) or [words](http://processingjs.org/learning/basic/words/) example in Chrome (48) or IE (11), and you get nice, relevant examples; open the same in Firefox (44), and you get an empty canvas for both. What gives?

**Comment by GoToLoop** [comment]
I've opened those 2 samples in Cyberfox 43.0.2 & Waterfox 44.0.3 in my 64-bit Win7 laptop.
(Both of them are Firefox-based browser btW.)
And both work as fine as my 64-bit Chrome-based SlimJet 7.0.8.0 (47.0.2526.73).

**Comment by Gutza** [comment]
You're right, after you confirmed it worked for you I tested with a vanilla Firefox profile and it works for me as well. I'll have to investigate this further; thank you for testing this and letting me know.

**Comment by Gutza** [comment]
Ok, I'm feeling quite silly now – I went ahead full steam on investigating this, restarting Firefox from scratch in order to start disabling extensions and the whole shebang. But as soon as I restarted the damned thing it just worked. So yeah, it was a case of the old "have you tried stopping it and starting it again"; sorry for wasting your time.
