### ISSUE TITLE
Empty Processing.instances

### ISSUE THREAD

**Issue by jansendup** [processing-js/processing-js#233]
After "Merge pull request #126 from wardsky/reload-fix" the following example doesn't function properly (See comments for details):

```
<html>
<head>
  <script src="processing.js"></script>
</head>
<body>
<p><canvas id="canvas1" width="200" height="200"></canvas></p>

<script id="script1" type="text/javascript">
function sketchProc(processing) {
  processing.draw = function() {
     // Draw something
  };
}
var canvas = document.getElementById("canvas1");
var p = new Processing(canvas, sketchProc);
console.log(Processing.instances); // Works fine. Prints out an array with one element
</script>

<script id="script2" type="text/javascript">
console.log(Processing.instances); // Something is wrong. This prints out an empty array.
</script>

</body>
</html>
```

Basically the processing instance de-registers or exits once the code within a script tag completed execution.

**Comment by Pomax** [comment]
hm, that is odd. If you want to investigate why this is now happening I'll be happy to take that, other I'll probably look at this next weekend.

**Comment by jansendup** [comment]
Investigating this now. It seems in 1.4.8 Processing.reload never gets called in that example but in 1.4.9 it does.

**Comment by jansendup** [comment]
Ok I think I know what is wrong. In 1.4.8, in contrast to 1.4.9, the init function doesn't call each instance's exit() method before recreating the Processing.instances list. The init function in 1.4.9 is actually correct in that it removes all instances properly and automatically creates new instances for all processing sources in die document. The problem however is that instances registered with user javascript don't get recreated. The fact that 1.4.8 and previous versions worked was actually a bug.

The workaround to this problem would be to call Processing.disableInit() to disable automatic loading of all sketches on the page. This would around should be documented in the getting started pages I think. The examples on those pages doesn't work for 1.4.9 and up.

I would recommend separate lists of processing instances. One for auto loaded sketches and another for manually created instances. However I don't have full perspective of the overall processing.js and its use cases so this might not be a valid suggestion.

**Comment by Pomax** [comment]
Thing is, though, that the "pure API" use of Processing.js isn't really supported anymore, given that there are way better graphics libraries out there if you want to write "graphics stuff using Javascript" rather than programming in Processing and wanting that to run on the web without applets.

If you want to work in JS, then you have things like paper.js, d3.js, or even something like p5.js (if you want to stay closer to the Processing idea). So I'd rather advocate that rather than make sure people who use the library as a "pure JS graphics library" are well-served by Pjs.

**Comment by prescod** [comment]
I assume this is the same problem.

This program works:

https://trinket.io/library/trinkets/3aee78aed9

If I change the 1.4.8 to 1.4.9 it doesn't anymore:

https://trinket.io/library/trinkets/12dd54398d

This is quite frustrating and pretty time wasting...

**Comment by Pomax** [comment]
Except v1.4.9 got released in Jan 4, 2015, so as unfortunate as it may be for you, the fact that a change three and a half years ago broke something is well beyond too late.  The API-only use of Processing.js was deprecated and removed years ago. In 2018 if you want a true native JS processing-like language, the officially processing-endorsed [p5.js](https://p5js.org/) is what you want.
