### ISSUE TITLE
the print command doesn't open the console

### ISSUE THREAD

**Issue by duianto** [processing-js/processing-js#237]
### Summary
When typing a print command on this page:
http://processingjs.org/tools/processing-helper.html
then the console at the bottom of the page doesn't open.

The console opens when a println command is written.

### Steps to reproduce
On the page:
http://processingjs.org/tools/processing-helper.html

1. type: `print("test");`
2. press the [Run] button below the "Processing Code" textarea, 
3. the console at the bottom of the page doesn't open.
4. below the print command in step 1, 
5. type: `println("test2");`
6. now the console opens and it shows:
7. `testtesttest2`

### Expected behavior
When running a print command, then the console should open 
and show it's output.

### Actual behavior
When running a print command, then the console doesn't open,
a println command needs to be written after it to open the console.

### Environment
OS: Windows 7 Home Premium 64 bit
Browser: Google Chrome 49.0.2623.112 (Official Build) m (32-bit)

### Discovery
The issue was discovered in the khan academy code editor:
https://www.khanacademy.org/computer-programming/new/pjs

And the issue was reported on the khan/live-editor github page:
https://github.com/Khan/live-editor/issues/574

There it was suggested that processing-js is the likely source, 
since the processing-helper page:
http://processingjs.org/tools/processing-helper.html
has the same console issue.

**Comment by Pomax** [comment]
thanks for reporting this! There aren't many people working on processing.js at the moment, but if you are interesting in getting this fixed, I'll be happy to point you in the right direction. The console print functionality is housed in https://github.com/processing-js/processing-js/blob/master/src/Helpers/PjsConsole.js with the `print` function defined on https://github.com/processing-js/processing-js/blob/master/src/Helpers/PjsConsole.js#L110 and the `println` function defined on https://github.com/processing-js/processing-js/blob/master/src/Helpers/PjsConsole.js#L119

**Comment by duianto** [comment]
I'm new to github and haven't done any big programming projects, 
so i might be over my head, but i might have found the solution, 
i also noticed an assignment difference between the print and println functions, 
and a small style issue in the file:
https://github.com/processing-js/processing-js/blob/master/src/Helpers/PjsConsole.js

#### Possible solution:
These lines:
L120-124:
```
    if(!added) {
      document.body.appendChild(style);
      document.body.appendChild(e.wrapper);
      added = true;
    }
```
that seem to add the console div (e.wrapper) to the body tag, 
are only called from the println function, 
but this line:
L127: `e.print.apply(e, args);`
seem to always call the print function from the println function.

Then the solution might be to move the lines L120-124 
from the println function, into the print function on L111, 
resulting in the print function looking like this:
```
  e.print = e.log = function () {
    if(!added) {
      document.body.appendChild(style);
      document.body.appendChild(e.wrapper);
      added = true;
    }
    var args = Array.prototype.slice.call(arguments);
    t = args.map(function(t, idx) { return t + (idx+1 === args.length ? "" : " "); }).join('');
    if (e.BufferArray[e.BufferArray.length - 1]) e.BufferArray[e.BufferArray.length - 1] += (t) + "";
    else e.BufferArray.push(t);
    e.javaconsole.innerHTML = e.BufferArray.join('');
    e.showconsole();
  };
```
and the println function ends up looking like this:
```
  e.println = function () {
    var args = Array.prototype.slice.call(arguments);
    args.push('<br>');
    e.print.apply(e, args);
    if (e.BufferArray.length > e.BufferMax) {
      e.BufferArray.splice(0, 1);
    } else {
      e.javaconsole.scrollTop = e.javaconsole.scrollHeight;
    }
  };
```

##### An assignment difference:

The print function gets assigned to both e.print and e.log:
L110: `e.print = e.log = function () {`

but the println function is only assigned to e.println
L119: `e.println = function () {`

maybe both or neither should have the `e.log` assignment.

##### A small style issue

I also noticed that the if and else statements with a single line of code, 
are written on one line throughout the js file, except in the println function 
where they are written with braces "{}" and the single lines of code are 
indented on the line below.

To make the js file conform to the same style, then maybe lines L128-132 
should be changed 
from:
```
    if (e.BufferArray.length > e.BufferMax) {
      e.BufferArray.splice(0, 1);
    } else {
      e.javaconsole.scrollTop = e.javaconsole.scrollHeight;
    }
```

to:
```
    if (e.BufferArray.length > e.BufferMax) e.BufferArray.splice(0, 1);
    else e.javaconsole.scrollTop = e.javaconsole.scrollHeight;
```

**Comment by atgeflu** [comment]
With the merge of the fix, I'd say we can close this issue.

**Comment by Pomax** [comment]
good  catch.
