### ISSUE TITLE
PVector::copy was not implemented

### ISSUE THREAD

**Issue by CapacitorSet** [processing-js/processing-js#239]
The following minimal code example fails, with error `TypeError: a.copy is not a function`.

``` processing
void setup() {
    PVector a, b;
    a = new PVector(0, 0);
    b = a.copy();
}
```

**Comment by GoToLoop** [comment]
Use the `@Deprecated` **get()** method or await for my very old pull request be approved:
https://GitHub.com/processing-js/processing-js/pull/201

**Comment by CapacitorSet** [comment]
Oh man, that's a 1-year-old PR. Good luck getting that approved! For now, I'll just use `b = new PVector(a.x, a.y);`.

**Comment by GoToLoop** [comment]
Just use **get()** in place of **copy()**: `b = a.get();`  ;-)

**Comment by CapacitorSet** [comment]
But get() is deprecated, it's not nice to use deprecated methods :P
Am 01.05.2016 21:00 schrieb "GoToLoop" <notifications@github.com>:

**Comment by KevinWorkman** [comment]
Has there been any movement on this?

**Comment by GoToLoop** [comment]
See here: https://github.com/processing-js/processing-js/pull/201

**Comment by Pomax** [comment]
There is no active development on Processing.js, so the best way to get problems fixed is to file your own PR, or get someone else who is affected by the problem to help out write a PR. Or, if you're lucky, someone else already filed one and you can help vet the code/testing etc

@GoToLoop: there's a lot of unadressed review notes on the PR you linked, are you still interested in addressing them so the code can move forward?

**Comment by CapacitorSet** [comment]
@Pomax, are you interested in finding maintainers? I would be glad to pick up this project.

**Comment by Pomax** [comment]
always! if you're interested in becoming a maintainer, shoot me an email (listed on [my profile](https://github.com/Pomax)) and I'll be happy to help figure out an approach!

**Comment by GoToLoop** [comment]
@CapacitorSet, I've updated my _**PVector**_ pull request.  
It's not aimed to be approved. Rather just a base for a future pull.
There's also a copy of it here: https://gist.GitHub.com/GoToLoop/acbf106aa784820aff23
