### ISSUE TITLE
PIE constant not defined

### ISSUE THREAD

**Issue by JamesWClark** [processing-js/processing-js#242]
PIE constant is not defined in Processing.js

The Processing (not JS) docs have this example:
arc(50, 50, 80, 80, 0, PI+QUARTER_PI, PIE);

That's on the page, https://processing.org/reference/arc_.html

**Comment by Pomax** [comment]
These may have been introduced with Processing 3, marking as parity bug

**Comment by GoToLoop** [comment]
Processing 3 didn't introduce anything worthy but the new FX2D renderer.
All actual new stuff arrived by Processing 2. And Pjs is stuck w/ P1.

**Comment by Pomax** [comment]
fixed with #246
