### ISSUE TITLE
Contributing to processing.js

### ISSUE THREAD

**Issue by atgeflu** [processing-js/processing-js#247]
Hi guys,
I've seen that you're looking for people to contribute.
Though I'm not a seasoned developer at all, I think there are a few open issues where I might be able to write a fix. 
I already gave a shot at a handful (see #246).

Please let me know if you feel like you could use my contributions.

Cheers,
Jean-Noël

**Comment by Pomax** [comment]
Hi Jean-Noël,

absolutely, if you want to try your hand at a few tickets, that would be most appreciated! I'll review your PR today (one of the reasons Pjs needs devs is because I don't really have a lot of time, often not even "any" throughout a week), but from a cursory glance it looks like a nice clean fix.

**Comment by atgeflu** [comment]
Hi Mike,
Thanks for replying and taking the time to review my PR. 

I'll have a look at some of the other issues to see if I can find a fix for some of them. 
Let me know, if there's something I can do to lessen the workload on your side, be it when submitting PRs or otherwise, so that I don't end up giving you unnecessary work. 

Cheers,
Jean-Noël

**Comment by Pomax** [comment]
Cool! One thing that might be interesting is to further improve the code itself a little, to make it easier to work on - right now it's in the state it was in after an initial rewrite from single 20l line file to multiple files built with a node.js build process, but there's a lot of things that can be improved (the way files require each other, for instance).

Aside from that, some classes like PVector have fallen behind Processing 3.0's API, and some of the newer classes like the HashMap etc. don't have Pjs equivalents yet, so there's a fair bit of things you can work on if you like, let me know what might sound interesting and I'll be happy to help get you set up and hacking on the code!

**Comment by atgeflu** [comment]
Next I was thinking of having a go at the open issues for the `noise()` function, since that looked pretty interesting. 

Improving the code itself sounds like a good idea as well. Though I was thinking this was the kind of tasks I could be up to once I've fixed a number of issues, etc. and gotten a better feel/understanding for the code base. (Unless there's some easier task in that domain to tackle where one can't do much wrong)

I'll probably also have a look at what's new in Processing 3.0 to see if any of it looks like the kind of stuff I could implement for Pjs.

**Comment by Pomax** [comment]
yeah that sounds great - doing a full replacement of the noise functions might be a big step, so it's not a bad idea to first review the https://github.com/processing-js/processing-js/pull/246#issuecomment-229929088 issue, and fixing that, and then doing the replacement as a follow-up to that (always a good idea to split up the work as much as possible)

**Comment by atgeflu** [comment]
Concerning the https://github.com/processing-js/processing-js/pull/246#issuecomment-229929088 issue, I'm pretty confident, that this is due to a few commits that happened after the last update of the processing.js file. Since the processing.js file hasn't been updated since, what happens is that building it automatically also includes these other changes.

**Comment by Pomax** [comment]
let's leave it in then.

**Comment by atgeflu** [comment]
Thanks for merging my PR. Should I delete my branch now?

I've added another PR for a simple fix. 

Analyzing the noise function is probably going to take some more time. So far the implementation looks like a regular Perlin noise implementation.

**Comment by Pomax** [comment]
if you don't want to keep your branch around (I usually don't) then it is now safe to delete it.

**Comment by Pomax** [comment]
as for noise: let's discuss the progress/work in its issue, and then I will close this one, since you're getting well on the road to contributing, with a PR landed and another in the pipeline =)
