### ISSUE TITLE
KeyboardEvent.keyIdentifier to be removed very soon

### ISSUE THREAD

**Issue by jseakle** [processing-js/processing-js#262]
All my processing.js projects now cause

`'KeyboardEvent.keyIdentifier' is deprecated and will be removed in M53, around September 2016. See https://www.chromestatus.com/features/5316065118650368 for more details.`

to show in the Chrome console. I assume this is because processing.js outputs this function, and thus basically all projects that use keyboard input will break on Chrome when this change goes through.

**Comment by Pomax** [comment]
Hm, that is very odd, as Processing.js does not use `KeyboardEvent.keyIdentifier` (nor just `keyIdentifier`) anywhere in the code. Are you sure this is triggered in Pjs?

**Comment by jseakle** [comment]
Sorry, I'm an idiot – it's actually a Chrome extension causing it whenever a key is pressed in any Chrome window. I had checked some other sites and seen that they didn't generate it, but I didn't actually press any keys on them >_>
