### ISSUE TITLE
rectMode(CORNERS) from (x,y) to (0,0)

### ISSUE THREAD

**Issue by JamesWClark** [processing-js/processing-js#263]
It should be possible to run `rectMode(CORNERS)` and anchor a rectangle from bottom-right to top-left origin (0, 0).

    // doesn't work, but should
    rectMode(CORNERS);
    rect(100, 100, 0, 0);

To highlight the problem further, consider it is currently possible to draw from bottom-right to a top-left negative. This code works:

    rectMode(CORNERS);
    rect(100, 100, -1, -1);

**Comment by Pomax** [comment]
Looks like this was caused by  the 2d context code doing the check for "do we have a numerical width and height" check incorrectly.  Fixed and v1.6.2 pushed.
