### ISSUE TITLE
createShape() seems not defined

### ISSUE THREAD

**Issue by GoldenQubicle** [processing-js/processing-js#266]
Had a sketch that worked online, then refactored a class by using the createShape() function, which broke the online functionality. Upon investigation it turned out createShape() is not in the reference. Moreover, after making a workaround the sketch now runs online again. Being new to all this I have no clue how to go about fixing it, however, happy to learn. :)

edit: [linkie to PS reference](https://processing.org/reference/createShape_.html)

**Comment by Pomax** [comment]
Processing.js has not seen a lot of development for parity for a while now, so overall you can expect it to be API 2.0 comformant, not API 3.0, which means it doesn't support `createShape` (amongst quite a few other functions and object types)

**Comment by GoToLoop** [comment]
Actually **createShape()** is Processing 2! Current parity for Pjs is still pretty stuck at Processing v1.5.1 w/ few P2 features thrown in.

**Comment by Pomax** [comment]
marking as duplicate of https://github.com/processing-js/processing-js/issues/260
