### ISSUE TITLE
hook up

### ISSUE THREAD

**Issue by mweels** [processing-js/processing-js#270]
help with learning math 
hook to container machine services
buy and sell libraries
typescript version

thank you

I buy you beer

**Comment by mweels** [comment]
Done yet ;)

**Comment by mweels** [comment]
Paneling would also be nice.

**Comment by Pomax** [comment]
I have no idea what you're asking, but I can tell you that Processing.js itself is only about supporting the Processing API insofar as it did that in the past, and is currently stalled. https://github.com/processing-js/processing-js/blob/master/CONTRIBUTING.md still applies.
