### ISSUE TITLE
println does not deal with a literal arrays

### ISSUE THREAD

**Issue by lgto4** [processing-js/processing-js#272]
`println([ 1, 2 ]);` causes gripes from Yoko Oh Noes.

**Comment by lgto4** [comment]
Oops.  This was meant for Khan Academy's rendition of Processing.js.

**Comment by Pomax** [comment]
Hm, did they fork their own copy and decided to move ahead on theirs rather than contributing back to Processing.js?

**Comment by GoToLoop** [comment]
That `[]` way of instantiating arrays is JS specific and you wouldn't accept that anyways!  :P
