### ISSUE TITLE
console.log in Drawing2D.rect

### ISSUE THREAD

**Issue by craigmalone** [processing-js/processing-js#275]
In the commit on 2-Oct-2016 "improved width/height check in 2d context rect()" the following line was added to Processing.js in the Drawing2D rect function:

      `line 8502:      console.log(x,y,width,height);`

Was this intended or is it left over debug?

It results in a large amount of console output when rendering many rectangles (as my project currently does).

**Comment by Pomax** [comment]
definitely not intended.
