### ISSUE TITLE
Processing.js closes active Processing session when set

### ISSUE THREAD

**Issue by kfrajer** [processing-js/processing-js#281]
This is to document a bug in the processing IDE. I am using processing 3.3 Win10 x64. This is what happens. I open Processing and it starts in java mode. I switched to javascript mode and the window closes. I tried to restart processing and it won't open any new sketch window. Then, I decided to open a pde file and processing runs and opens the file in JavaScript mode. Good. Then I create a new sketch as a next step and it fails, throwing an error in the console:

> Error while assigning the sketch template.

I can switch back to Java mode and everything goes back to normal. In addition, this behavior is not observed in Processing 3.1.1.

This issue was also posted here
https://forum.processing.org/two/discussion/21590/processing-js-closes-active-processing-session-when-set

Previous related issue:
https://github.com/fjenett/javascript-mode-processing/issues/35

kfrajer

------------------------
Thank you for finding a bug in Processing.js, or having a feature request you'd like to see added.

Processing.js is not under active maintenance at the moment, lacking developers that have the time
to work on it. As such, any bug you find might take a long time to get a fix. However, if you're
interested in fixing things yourself, I (Pomax) will be more than happy to review your suggested
code changes and merge them in if they fix the problem you were having without introducing problems
due to side effects your code might have.

**Comment by Pomax** [comment]
Please file this over on https://github.com/processing/processing, as this is the repository for the Processing.js library, and was developed independently of Processing or its IDE
