### ISSUE TITLE
BUG: jsdom.jsdom is not a function

### ISSUE THREAD

**Issue by westurner** [processing-js/processing-js#295]
The call signature for jsdom has changed:

```javascript
// old
jsdom.jsdom(html, options);
// new
document = new jsdom.JSDOM(html, options);
window = document.window;
```
References:
- https://github.com/rstacruz/jsdom-global/pull/23/files

Error:
```
../node_modules/processing/lib/processing.js:14
  , document = jsdom.jsdom('<!doctype html><html><head></head><body></body></html>')
                     ^

TypeError: jsdom.jsdom is not a function
```

Solutions:
- Change processing.js:14 to the new jsdom form
- Specify jsdom < 9.12.10 in package.json
  - https://github.com/rstacruz/jsdom-global/issues/22

.

- I installed with ``npm install --save processing``
  - https://www.npmjs.com/package/processing
    (which appears to be way out of date, as there's no mention of jsdom in this Processing.js, sorry)
    - The correct package is (as it clearly reads in the README):
       https://www.npmjs.com/package/processing-js

**Comment by westurner** [comment]
Aha!

p5.js and IJavascript are what I was looking for.

- https://github.com/processing/p5.js
- https://github.com/n-riesco/ijavascript/issues/131

**Comment by Pomax** [comment]
I was about to say - processing.js does not rely on jsdom =)
