### ISSUE TITLE
p.loop should use requestAnimationFrame where available.

### ISSUE THREAD

**Issue by zya** [processing-js/processing-js#92]
`p.loop` should use `requestAnimationFrame` where available instead of `setInterval`.

**Comment by Pomax** [comment]
requestAnimationFrame is 60fps. Processing's default rate is 45. There is literally no way to match Processing's intentionally  framerate based rendering concept to render pipeline that does its utmost best to destroy the very notion of framerate based animation. I'm closing this simply because webpages should totally use requestAnimationFrame, and Processing sketches should totally not because of their explicit frame based rendering.

**Comment by arxpoetica** [comment]
The last comment is not fully true. It's still best to rely on RAF. The end of this article explains a method to utilize both techniques, thus still getting the value out of RAF but getting frame rate: http://creativejs.com/resources/requestanimationframe/

**Comment by Pomax** [comment]
If you're up for writing a PR that introduces that change, and the ref tests show improved performance, I'll happily add it in, but as a frame-based animation tool there is not enough to justify moving to requestAnimationFrame and then bake framerate limiting back in by relying on additional setTimeout restrictions.

**Comment by jwdunn1** [comment]
Or...for those interested, combine the best of both worlds as follows:
<pre><code>
void setup() {
  size(200, 200);
  noLoop();  // so draw() will not loop automatically
  animateGated(); // <-- run at a gated framerate
  //animate(); // <-- or run unbridled
}

float x = 0;
void draw() {
  background(204);
  x = x + 1;
  if (x > width) x = 0;
  line(x, 0, x, height); 
}

void animate() { // runs at 120fps on a 120hz monitor
  requestAnimationFrame( animate );
  redraw();
}

Date d=new Date();
long now, then= d.getTime(), delta,
     interval = 20; // framerate target 50fps: 1000/50=20

void animateGated() { // runs at target fps
    requestAnimationFrame( animateGated );
    now = new Date();
    delta = now - then;
    if (delta > interval) { // regulate with 'interval' value
      then = now - (delta % interval);
      redraw();
    }
}
</code></pre>
Gating based on: http://ow.ly/McNIs

**Comment by Pomax** [comment]
instead of using `new Date` you can use `millis()`, and reduce the code depdency on JavaScript a bit more.

**Comment by hlfcoding** [comment]
>  I'm closing this simply because webpages with canvas animations or even DOM animations should totally use requestAnimationFrame, but Processing sketches should totally not because of their explicit frame based rendering.

Why not default to using `requestAnimationFrame` _unless_ frameRate gets called and set to something specific? So basically there'd be two different update systems, and the coder should have at least the _option_ to switch between them. I think the default should favor performance over possibly unused configurability. Anything that runs in a browser should behave like a good citizen. Taking up CPU when the tab is inactive does not count, and prevents serious use cases of embedded sketches in typical pages, like processingjs.org does for its own site banner.

**Comment by Pomax** [comment]
as unpleasant it is to hear this: PRs welcome, but I won't be putting this in myself due to time constraints.

**Comment by harrislapiroff** [comment]
Not unpleasant news at all. I'm uncertain I have the time to work on this, but I appreciate the go ahead! I'll open a new issue if I decide to work on this.

**Comment by Domiii** [comment]
I realized that without using `requestAnimationFrame`, processing.js becomes a flickering quagmire (given a large enough canvas), I decided to produce a quick-fix that would not adhere to general open-source standards, but it gets the job done. Here is a patch for [processing.js v1.4.8](https://raw.githubusercontent.com/processing-js/processing-js/v1.4.8/processing.js):

```Diff
13529c13529,13533
<       clearInterval(looping);
---
>       
>       // requestAnimationFrame edit
>       //clearInterval(looping);
>       looping = false;
>       
13531a13536,13548
>     
>     
>     // requestAnimationFrame edit
>     var _doDraw = function() {
>       requestAnimationFrame(function() {
>         if (!looping) { return; }
>         
>         curSketch.onFrameStart();
>         p.redraw();
>         curSketch.onFrameEnd();
>         _doDraw();
>       });
>     };
13549,13558c13566,13580
<       looping = window.setInterval(function() {
<         try {
<           curSketch.onFrameStart();
<           p.redraw();
<           curSketch.onFrameEnd();
<         } catch(e_loop) {
<           window.clearInterval(looping);
<           throw e_loop;
<         }
<       }, curMsPerFrame);
---
>       // looping = window.setInterval(function() {
>       //   try {
>       //     curSketch.onFrameStart();
>       //     p.redraw();
>       //     curSketch.onFrameEnd();
>       //   } catch(e_loop) {
>       //     window.clearInterval(looping);
>       //     throw e_loop;
>       //   }
>       // }, curMsPerFrame);
>       
>       // requestAnimationFrame edit
>       looping = true;
>       _doDraw();
>       
13594a13617,13620
>       // requestAnimationFrame edit
>       //window.clearInterval(looping);
>       looping = false;
>       
13596d13621
<       window.clearInterval(looping);
21366c21391,21393
<       var keyTrigger = curSketch.options.globalKeyEvents ? window : curElement;
---
>       //var keyTrigger = curSketch.options.globalKeyEvents ? window : curElement;
>       var keyTrigger = window;
>       
```

**Comment by Pomax** [comment]
can you please file that as PR?

**Comment by Domiii** [comment]
Done. Here is the [PR](https://github.com/processing-js/processing-js/pull/210). Note the warnings though:

1. This fix defeats portability (see [official requestAnimationFrame docs](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame#Browser_compatibility))
2. ignores any frame-rate settings 
3. and is not thoroughly tested

**Comment by Pomax** [comment]
I see. Unfortunately, the first two are crucial to Pjs, which is why I've *not* moved it to requestAnimationFrame.

**Comment by Domiii** [comment]
I thought so. The flickering is a huge issue though. We are currently using Khan Academy for our class. There, due to the small canvas (fixed at 400x400), the flickering rarely becomes apparent. But now, I want to move toward the real web and sadly, when using Processing (or any sort of animation based on `setInterval` on a `canvas`) on a really big `canvas`, it just becomes unwatchable. The flickering canvas issue is also highlighted in [this SO post](http://stackoverflow.com/questions/2795269/does-html5-canvas-support-double-buffering) (scroll down for examples).

If it helps, [here is a polyfill for requestAnimationFrame](https://gist.github.com/paulirish/1579671).

**Comment by Pomax** [comment]
given the [caniuse](http://caniuse.com/#feat=requestanimationframe) matrix, a simple `if (requestAnimationFrame) { use Request Animation Frame ) else { don't }` would be enough, but there would need to be fixes to the frameRate function and the frame slicer, so that RAF calls are not automatically honoured, but are checked for "when was the last actual draw call, and has it been at least 1/framerate seconds since then".

**Comment by jwdunn1** [comment]
To run at a specified frame rate using rAF, simply incorporate the animateGated() function I listed in my comment earlier (Apr 27). It works perfectly in my own framework.

**Comment by Pomax** [comment]
that'll need more work though: the `draw` loop has to reset a whole bunch of things (all the draw-contextual settings need to reset each call) so it'd need some more code added: https://github.com/processing-js/processing-js/blob/master/src/Processing.js#L4000

**Comment by Pomax** [comment]
@jwdunn1 do you have a blog post or other online posting that people can be pointed to in case they run into the same issues?
