### ISSUE TITLE
touch events not working after v1.4.1

### ISSUE THREAD

**Issue by emielch** [processing-js/processing-js#99]
When I try to use the touch events with a version of processing.js after 1.4.1 I get the following error in the console: "Uncaught ReferenceError: eventHandlers is not defined" and the touch events are not working, when using 1.4.1 it works but i get another message in the console: "Uncaught InvalidStateError: Failed to execute 'dispatchEvent' on 'EventTarget': The event is already being dispatched.".
I used the example code from this page: http://www.bradchen.com/blog/2011/04/processing-js-touch-events
This problem occurred with chrome on android, safari on iOS and when using the touch screen emulator of chrome on windows to try it on the pc.
When using v1.4.1 it works, with v1.4.7 and after it doesn't and I get the first error message.

**Comment by karger** [comment]
I'm running into the same issue described here; was there a problem with the PR?
